on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Run markdown link checker
      uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1.0.14
      with:
        config-file: '.github/workflows/markdown.links.config.json'
        folder-path: 'website/'
